id: IC44D20DA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:59:18+00:00'
last_modified: '2022-06-08T03:29:13.677482+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17443
  title: མ་རྡུལ་དངོས་ལུགས་རིག་པའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    D8F6:
      image_group_id: I2PD17959
      title: ''
      total_pages: 582
      order: 1
      base_file: D8F6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
