id: P005494
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17443
  title: མ་རྡུལ་དངོས་ལུགས་རིག་པའི་རྣམ་བཤད།
  author: ''
  volumes:
    823ee6f11fed43dc99738d6291fd31cb:
      image_group_id: I2PD17959
      title: ''
      volume_number: 1
      total_pages: 582
      base_file: v001.txt
